### ISSUE TITLE
ability to mark entities as 'removed'

### ISSUE THREAD

**Issue by Schaubroeck** [v-ict-or/oslo_xml_schemas#10]
We need a way to mark that an entity was removed from the dataset.
This is required for incremental updates in an import-export scenario.

**Comment by laurensdv** [comment]
We suggest a (boolean) value included in the metadata identifying a resource (oslo:Identifier) to mark whether a resource is still 'active' or not. Changing this state to 'unactive' or 'active:False' rather than deleting the resource ensures incremental update and verifying which entities are no long relevant in the dataset for import.

**Comment by laurensdv** [comment]
Changes should be reflected in new branch shared_catalogue_extension: https://github.com/rafbuyle/oslo_xml_schemas/tree/shared_catalogue_extension

## Identifier

| Conceptueel | XML Schema | RDF |
| --- | --- | --- |
| Sleutel | cvb:Identifier | dcterms:identifier |
| Type | cvb:IdentifierType | dcterms:type |
| Bron | cvb:IssuingAuthority, | adms:schemeAgency, |
|  | cvb:IssuingAuthorityID | dcterms:publisher |
| Wijzigingsdatum | cbc:IssueDate | dcterms:issued |
| Revisie | ovc:revisionOf | prov:wasRevisionOf |
| Actief | ovc:isActive | oslo:isActive |
